<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<RootNamespace>DarkVox.Server</RootNamespace>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\dark-vox.shared\dark-vox.shared.csproj" />
	  <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
	  <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.7" />
	</ItemGroup>	
</Project>