<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>OpenRender.Text</RootNamespace>
    <AssemblyName>OpenRender.Text</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Shaders\text.frag" />
    <None Remove="Shaders\text.vert" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Shaders\text.frag">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Shaders\text.vert">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="SixLabors.Fonts" Version="2.1.3" />
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
		<PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.7" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\OpenRender\OpenRender.csproj" />
	</ItemGroup>
</Project>
