#version 460

layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;

layout(std430, binding = 0) buffer ssbo_height { float height[]; };
layout(std430, binding = 1) buffer ssbo_blocktypes { uint blocktype[]; };
layout(std430, binding = 2) buffer ssbo_chunk_indices { uint chunkIndices[]; };

uniform int chunkSize;
uniform int chunkYSize;
uniform int waterLevel;


const uint BlockTypeNone = 0u;
const uint BlockTypeWaterLevel = 1u;
const uint BlockTypeRock = 2u;
const uint BlockTypeSand = 3u;
const uint BlockTypeDirt = 4u;
const uint BlockTypeGrassDirt = 5u;
const uint BlockTypeGrass = 6u;
const uint BlockTypeSnow = 7u;
const uint BlockTypeBedRock = 8u;
const uint BlockTypeGravel = 9u;

float GetHeight(uint chunkIdx, uint lx, uint lz) {
    uint chunkArea = uint(chunkSize * chunkSize);
    uint baseIndex = chunkIdx * chunkArea;
    return height[baseIndex + lx + lz * uint(chunkSize)];
}

uint CalcBlockType(int maxHeight, uint x, uint y, uint z) {
    uint blockAltitude = y;
    uint bt;
    if (blockAltitude > uint(maxHeight))                                       bt = BlockTypeNone;
    else if (blockAltitude == uint(maxHeight))                                 bt = BlockTypeGrassDirt;
    else if (blockAltitude < maxHeight && blockAltitude >= uint(maxHeight) - 2)bt = BlockTypeDirt;
    else if (blockAltitude < uint(maxHeight) - 2)                              bt = BlockTypeRock;

    if (blockAltitude <= uint(waterLevel)) {
        if (bt == BlockTypeNone && blockAltitude == uint(waterLevel))           bt = BlockTypeWaterLevel;
        else if (bt != BlockTypeNone && blockAltitude + 1u >= uint(waterLevel)) bt = BlockTypeSand;
        else if (bt != BlockTypeNone && blockAltitude + 1u <  uint(waterLevel)) bt = BlockTypeBedRock;
        else if (blockAltitude < 3u)                                            bt = BlockTypeBedRock;
    }

    return bt;
}

void main() { 
    
    uint lx = gl_LocalInvocationID.x;   // chunk local X
    uint lz = gl_LocalInvocationID.y;   // chunk local Z

    uint group = gl_WorkGroupID.x;                      // 0..N-1 of this dispatch
    float h = GetHeight(group, lx, lz);
    int normalizedHeight = int(round( h * float(chunkYSize - 1) ));
    uint voxelCount = uint(chunkSize) * uint(chunkSize) * uint(chunkYSize);
    uint base = gl_WorkGroupID.x * voxelCount;  //  packed per-dispatch

    // SIGNED y loop (avoid uint underflow) and 0..chunkYSize-1 range
    for (int y = chunkYSize - 1; y >= 0; --y) {
        uint blockIdx = lx + lz * uint(chunkSize) + uint(y) * uint(chunkSize * chunkSize);
        uint bt = CalcBlockType(normalizedHeight, lx, uint(y), lz);

        blocktype[base + blockIdx] = bt; 
    }
} 
