#version 460

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

struct IndirectCmd {
    uint Count;
    uint InstanceCount;
    uint FirstIndex;
    uint BaseVertex;
    uint BaseInstance;
};
layout(std430, binding = 12) buffer ssbo_indirect { IndirectCmd cmds[]; };
layout(std430, binding = 14) buffer ssbo_sum { uint total; };

uniform int drawCount;

void main()
{
    uint gid = gl_GlobalInvocationID.x;
    if (gid >= uint(drawCount)) return;
    atomicAdd(total, cmds[gid].InstanceCount);
}
